#!/bin/sh

# make sure we never run 2 rsync at the same time
lockfile="/tmp/alpine-mirror.lock"
if [ -z "$flock" ] ; then
  exec env flock=1 flock -n $lockfile "$0" "$@"
fi

src=rsync://rsync.alpinelinux.org/alpine/
dest=/var/www/localhost/htdocs/alpine/

# Lots of exclusions. If you want more version or platforms, remove as necessary
exclude="--exclude v2.* \
  --exclude *ppc64le* \
  --exclude *s390x* \
  --exclude *armhf* \
  --exclude *aarch64* \
  --exclude edge \
  --exclude v3.0 \
  --exclude v3.1 \
  --exclude v3.2 \
  --exclude v3.3 \
  --exclude v3.4 \
  --exclude v3.5 \
  --exclude v3.7"

mkdir -p "$dest"
/usr/bin/rsync \
        --archive \
        --update \
        --hard-links \
        --delete \
        --delete-after \
        --timeout=600 \
        --delay-updates \
        $exclude \
        "$src" "$dest"
